name: Test our Secret Value

on: [workflow_dispatch] 

env:
  ## Sets environment variable
  
  USERNAME: ${{secrets.USERNAME}}    
  PASSWORD: ${{secrets.PASSWORD}}    
  JWT: ${{secrets.JWT}}    
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i  
      - name: Run test script
        run: npm run test
